### ISSUE TITLE
Awesome work!

### ISSUE THREAD

**Issue by davidbwaters** [mattDavo/Yippy#1]
Wow!  I was searching Github after wondering what the state of FOSS clipboard tools was for MacOS and came across your project.  Seriously awesome work.  I'm still playing around with the release, but the feature set and design are more mature than anything else I've seen.  

And it's _native_!  A million Electron tools pop up all the time, some of which are attractive, but that seems like a terrible platform for something always running in the background and using 100x more resources than a native implementation would...  I don't want to have to set aside a half of gig of ram for my clipboard to work properly.

I couldn't believe it had no stars, either, so I wanted to show support.  Give yourself a star, buddy!  You deserve it!  Props for the blog and consistent maintenance.  I'll comment back with usage feedback when I get spend some time with it.  

As far as auto-updates go, maybe consider adding a Brew Cask, at least for the time being.  When you feel it's ready, I would submit it to ProductHunt.  It seems like a project that would be popular on there.  Also, I'm a designer and stay pretty busy nowadays, but if you need UI feedback or an artsy icon I'd contribute when I can find the time.  Peace.

**Comment by mattDavo** [comment]
Hey @davidbwaters! Thank you for checking it out, I hope you find it useful!

Yeah exactly, I definitely had that in mind, especially when you're copying lots of text or large images.

Thanks a lot, I appreciate that. There are a few things I know I need to sort out as well but I really look forward to your feedback.

Thanks for the advice, and I'm definitely no designer 😂, so if you have any UI feedback or a cool icon that would be much appreciated.

Cheers 😊

**Comment by davidbwaters** [comment]
Hey, I'm having trouble getting it to open on the latest Catalina.  Nothing happens when I tried to open it.  It didn't ask for accessibility access, so I added manually selected the app and add it to the list, but that didn't solve it. I tried the previous 2.0 release and had the same issue.  I have gatekeeper disabled.  I searched in Activity Monitor for a yippy related process and none were shown.  Any ideas?

**Comment by mattDavo** [comment]
Hey @davidbwaters, I had a look and I think the issue was to do with failing to load some fonts but it should be fixed now. Give [2.1.2](https://yippy.mattdavo.com/) a try and let me know how you get on.

**Comment by davidbwaters** [comment]
Yeah, that fixed it.  Thanks.  Awesome work.  I look forward to the right click options, etc.  I designed a few variations on a possible icon.  The app icon I need to work with the colors and variants to match macOS more, but I mocked up an attempt at a "Y" shape as scissors.  I'm attaching what I've come up with so far.  These are just screenshots but they are vector shapes in Sketch.  
![ic5](https://user-images.githubusercontent.com/5247627/75013914-323b7e80-5453-11ea-9d41-43a99ffa7643.png)
![Screen Shot 2020-02-21 at 2 30 07 AM](https://user-images.githubusercontent.com/5247627/75013936-3b2c5000-5453-11ea-8c32-7d014ca69626.png)
![Screen Shot 2020-02-21 at 2 29 40 AM](https://user-images.githubusercontent.com/5247627/75013945-3f586d80-5453-11ea-8d48-12d72a43693e.png)

**Comment by mehyaa** [comment]
Hey @mattDavo great work 👍🏻

I've been using MacOS more than a year now but I could still haven't found an application that can fill the void which [Ditto](https://ditto-cp.sourceforge.io/) filled on Windows.

Today I saw Yippy project on a list and gave it a try. I can say Yippy is the best in the ones which I've tried so far. And better looking (great looking actually). And more importantly open source 😎

There are a couple features which I've tought it would be great if Yippy did have... But hey look, they are on the TODO list. 😀

I have a little suggestion if you are interested in. It will be great if the list window can be centered (and maybe resizable) with an option.

I am looking forward to new releases.

**Comment by alongouldman** [comment]
I join in to the above. amazing app! I am really looking forward to the ability to cosumize the keyboard shortcut - since the shortcut you have now is preserved in mac for cutting-and-pasting. 
Anyways - thanks! Im not a swift dev so I can't really help on that one. If you need any python tasks - I am happy to help. 

thanks!

**Comment by mattDavo** [comment]
Hey guys! Thanks for all of the support, it is much appreciated and I'm glad you're liking it!

@davidbwaters the icon looks great, I like the rounded version you have in the large render!

@mehyaa and @alongouldman thanks for the suggestions! I'm fairly busy this week, but those two features shouldn't be too tough, so hopefully I can get them done for you in the coming weeks!

Cheers!

**Comment by alongouldman** [comment]
@mattDavo playing around a bit more: 
1. search is crucial actually, more then the shortcuts. 
2. images don't work for me when I copy an image. I get "unknown format" message instead. 
3. when working with multiple monitors, the pane is open always in the same one (even if my mouse and focus is in another)

thanks!

**Comment by mattDavo** [comment]
1,3 ok noted. They can be next in line.

2. Would you be able to give me an example, so that I can debug it myself?

Thanks 😄

**Comment by alongouldman** [comment]
this is what I get when I copy an image:

![image](https://user-images.githubusercontent.com/42400390/75237209-a1a0cd80-57c7-11ea-97f1-9e2514a795eb.png)

interesting though - When I click on image "copy image", it works fine. but when I take a snapshot and save into the clipboard (cmd+ctrl+shift+3), then I get this unknown format thingie.

**Comment by mattDavo** [comment]
Ok cool, that's really helpful. I'll look into that!

**Comment by mehyaa** [comment]
I think the TODO list, other feature requests mentioned here and the bugs should have their own issues for better tracking 🙂

**Comment by davidbwaters** [comment]
@mattDavo Cool, thanks.  Do you have a preference or feedback on the icon itself from the variations I posted?  Looking at them again I am kinda leaning towards the first one and the last one.  I want it to be reminiscent of a Y and scissors, if that wasn't apparent, but if people just see a cool shape that's fine too.  The one on the right kinda resembles the mac command button, for what that's worth.

![75013936-3b2c5000-5453-11ea-8c32-7d014ca69626](https://user-images.githubusercontent.com/5247627/75498946-8e902800-5996-11ea-8723-7c8323b7fc81.png)
