### ISSUE TITLE
Some ideas to borrow from Clipy?

### ISSUE THREAD

**Issue by Bartman0** [mattDavo/Yippy#13]
I am trying Yippy now after being an avid user of Clipy https://clipy-app.com .
One of the things Clipy has are menu's for one's own short texts.

For example I had a SQL menu with "select * from ", "group by ".
And a 'Me' menu with my name, adres, telephone details etc.

All of this easily accessible from the same Shift+Cmd+V shortcut.

What I missed in Clipy and was trying to add to it (but now I switched to Yippy why still do that?) is an option to use macro's in those menu items, like the date of today, the current time, and what have you.

I might try adding this now to Yippy, but I am still very fresh in macOS development let alone Swift.

Maybe these things are a piece of cake for you.

Thanks for Yippy!

**Comment by mattDavo** [comment]
Hey @Bartman0, thank you for your support!

Yeah I 100% agree and would love this feature as well. I have long visioned this feature to be implemented by "groups" and you can save your items to groups, which can be accessed by tabs (/filters) in the Yippy window.

I have said (a few times now 😅) that the next thing I would do is search. I have begun working on it, and would say it is about 20% complete. I can look at this after I have finished it.

Thank you for offering to add it yourself (I noticed you've already forked it), I would be happy to provide any assistance in the meantime. I wouldn't say that it is too difficult, nor simple. But it does require a fair chunk of changes across the app. However, they are not too macOS dev specific.

Cheers 😄

**Comment by mattDavo** [comment]
Closing as this has multiple requests which have dedicated issues:
- Groups/folders: https://github.com/mattDavo/Yippy/issues/24
- Macros: https://github.com/mattDavo/Yippy/issues/32
