### ISSUE TITLE
fundamentals

### ISSUE THREAD

**Issue by buxxb** [mattDavo/Yippy#17]
Hi Matt,

Fundamentals for UX in Yippy MVO.

1
click on the icon in menubar to get the clipboard

2
have an icon in the clipboard to get the preferences and/or option+ to get it

3
pin frequently used items [FUIs]

4
don't force blue if general settings are other colour, or just make it grey

5
click on item to paste and make window disappear. that's normal.

6
i can see you have a contextual menu saying options coming soon, which i hope allows pinning, among other things. but its v2.4. What was v1.0 to get this far? 

Good luck.

**Comment by mattDavo** [comment]
Hello,

> 1. click on the icon in menubar to get the clipboard

Won't be doing this unless there are many more requests.

> 2. have an icon in the clipboard to get the preferences and/or option+ to get it

https://github.com/mattDavo/Yippy/issues/31

> 3. pin frequently used items [FUIs]

Will be explored when solving https://github.com/mattDavo/Yippy/issues/24

> 4. don't force blue if general settings are other colour, or just make it grey

https://github.com/mattDavo/Yippy/issues/30

> 5. click on item to paste and make window disappear. that's normal.

Clicking is for selection as with most UIs, enter will paste the item.

> 6. i can see you have a contextual menu saying options coming soon, which i hope allows pinning, among other things. but its v2.4. What was v1.0 to get this far?

Do not be deceived by [semantic versioning](https://semver.org/), the changes between v1 and v2, were not big UX changes but backend changes that would break the existing experience.
