### ISSUE TITLE
Prevent copying from password managers like 1Password, KeePassXC, etc

### ISSUE THREAD

**Issue by karlhorky** [mattDavo/Yippy#18]
Hi there, first of all, thanks for this software, really cool! I'm currently using [Flycut](https://github.com/TermiT/Flycut), but I'm considering giving this a shot too :)

Would you be open to preventing saving from password manager pasteboard types such as:

- `org.nspasteboard.TransientType`
- `org.nspasteboard.ConcealedType`
- `org.nspasteboard.AutoGeneratedType`
- `com.agilebits.onepassword` 

I've seen these requests in other password managers before - such as https://github.com/TermiT/Flycut/pull/117

**Comment by mattDavo** [comment]
Done! https://github.com/mattDavo/Yippy/releases/tag/2.4.1

@karlhorky could you please confirm that it works for your workflow?

**Comment by karlhorky** [comment]
Ah, just trying out `2.4.1` with [KeePassXC](https://keepassxc.org/) on macOS and it appears to be copying the passwords still...

I looked at the list in Maccy and it appears that there are others that I missed:

https://github.com/p0deje/Maccy/blame/20e87f9880824e14a7a4f34d9575e90de68ccf11/README.md#L69-L83

**Comment by mattDavo** [comment]
Ahh gotcha, cheers. Will sort this out

**Comment by mattDavo** [comment]
Sorry try [2.4.2](https://github.com/mattDavo/Yippy/releases/tag/2.4.2) @karlhorky should work now.

**Comment by karlhorky** [comment]
Yayy, looks good! 🙌 💯  Thanks @mattDavo - going to try switching from Maccy to Yippy now! Closing.
