### ISSUE TITLE
Add a Homebrew Cask

### ISSUE THREAD

**Issue by karlhorky** [mattDavo/Yippy#19]
Hi @mattDavo !

Would you be open to having Yippy submitted as a Homebrew Cask? They have a [guide to adding a new cask](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md).

**Comment by mattDavo** [comment]
Yep. I'll take a look 👌

**Comment by karlhorky** [comment]
If there are any artificial barriers such as minimum 50 GitHub stars (can't remember where I saw this), I will help with getting the required stars :)

**Comment by mattDavo** [comment]
Yeah had a try @karlhorky, looks like it's not notable enough, not sure if all or any or these criteria need to be met:

```
 - GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```

**Comment by karlhorky** [comment]
Ok, tweeted, let's see! https://twitter.com/karlhorky/status/1350392499404222464

**Comment by mattDavo** [comment]
Thanks!

**Comment by aried3r** [comment]
Hey! Until this repo fulfills the necessary requirements, would it be an option to add a tap? It can live in a separate repo under your username. For example, users have their own, [like this one.](https://github.com/JakeWharton/homebrew-repo).

See also https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap and https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by karlhorky** [comment]
Ah just came back to the repo just now, and 94 stars!! ✨ 🙌

Looking forward to seeing this on Homebrew Cask! 🎉

**Comment by karlhorky** [comment]
@aried3r do you think that you could help with submitting this to Homebrew Cask?

**Comment by mattDavo** [comment]
Created a PR https://github.com/Homebrew/homebrew-cask/pull/106961 👌

**Comment by karlhorky** [comment]
Awesome, thanks Matt!

**Comment by mattDavo** [comment]
Merged!
