### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by mattDavo** [mattDavo/Yippy#2]
Hey @davidbwaters, yeah I like the last one, how does it look in the status bar, would you be able to mock that up? I'm just worried it could look a little too skinny...

![image](https://user-images.githubusercontent.com/13739650/75537114-8bff0280-5a6a-11ea-91c6-52f495a258bc.png)

**Comment by davidbwaters** [comment]
Sure I'll post a progress update soon.

**Comment by davidbwaters** [comment]
Hey, I've been tweaking the app icon.  I used the other version you liked.  I'll mock it in the status bar soon.
![AppIcon3](https://user-images.githubusercontent.com/5247627/76182323-cff4b480-619a-11ea-9137-f35bd8a6343f.png)

**Comment by mattDavo** [comment]
That looks awesome @davidbwaters, great work!

**Comment by davidbwaters** [comment]
thanks did a few iterations:
![ic7](https://user-images.githubusercontent.com/5247627/76478059-bdb68880-63dd-11ea-8825-4a2a06dfa30b.png)
![ic8](https://user-images.githubusercontent.com/5247627/76478060-c018e280-63dd-11ea-86fd-29d457eee785.png)

**Comment by davidbwaters** [comment]
Hey. Here are mockups of light dark menu bar icons.  I'm attaching a zip with a bunch of resources you can use however you want, but I might still refine the app icon when I can.  
![dk](https://user-images.githubusercontent.com/5247627/76487511-0af42380-63f9-11ea-86da-3abbfac42b74.png)
![lt](https://user-images.githubusercontent.com/5247627/76487516-0cbde700-63f9-11ea-9bd2-75bb19aa655d.png)
[Icons.zip](https://github.com/mattDavo/Yippy/files/4322282/Icons.zip)

**Comment by davidbwaters** [comment]
also, here is a shot of the current icon among other icons for reference (even though it won't be in the dock really)
![Screen Shot 2020-03-12 at 12 35 32 AM](https://user-images.githubusercontent.com/5247627/76487697-92da2d80-63f9-11ea-9fae-878a20eb4871.png)

**Comment by mattDavo** [comment]
This is awesome @davidbwaters! I'll add these in the next release! Hopefully soon!

**Comment by mattDavo** [comment]
New icons are in [2.2.0](https://github.com/mattDavo/Yippy/releases/tag/2.2.0)!
