### ISSUE TITLE
Overlay Window Cut Off on Second Monitor

### ISSUE THREAD

**Issue by karlhorky** [mattDavo/Yippy#20]
Hi @mattDavo ! 👋  Hope you are well.

If I use a second monitor with a lower resolution as my laptop screen, then Yippy gets cut off at the top (cannot see the "Yippy" title or the first item) 😱

**Comment by CollinsVakayil** [comment]
Yes, I've noticed the same issue when multiple monitors are hooked up Yippy gets cut off.

**Comment by mattDavo** [comment]
Resolved in https://github.com/mattDavo/Yippy/releases/tag/2.6.0

**Comment by mattDavo** [comment]
Resolved in https://github.com/mattDavo/Yippy/releases/tag/2.6.0

**Comment by karlhorky** [comment]
Great, testing now. I see that [you also also bumped the Homebrew Cask](https://github.com/Homebrew/homebrew-cask/pull/107229), thanks!!

**Comment by karlhorky** [comment]
@mattDavo getting a "Yippy can't be opened because Apple cannot check it for malicious software" error - maybe something wrong with code signing?

<img width="258" alt="Screen Shot 2021-06-13 at 10 47 14" src="https://user-images.githubusercontent.com/1935696/121800927-d93dbe00-cc34-11eb-86fa-1347c6c44f89.png">


I can open a new issue if you'd prefer too.

**Comment by karlhorky** [comment]
Clipping issue has been fixed though, looks great! 👍 Thanks again!

**Comment by mattDavo** [comment]
Hey @karlhorky, I think this has always been an issue (see [installation help](https://yippy.mattdavo.com/installation)). I think if you just replace the existing installed application it doesn't raise this again but if you delete and reinstall it does?  Unfortunately homebrew cask does delete then install to upgrade.

I looked further into the issue today and yeah you're right it's a code signing issue. It needs to be [notarized](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution) which runs checks that it isn't malicious. Unfortunately you need an Apple developer account to notarize, which I don't really want to pay for haha. However, I may consider it. Yippy is seeming to get a lot more traffic recently so I'm going to try and figure out how much it is being used and will reconsider if it is large enough.

**Comment by karlhorky** [comment]
Oh ok, understood. Wonder if a possibility for donations (eg. GitHub Sponsors, Patreon, Open Collective, etc) would help to offset the cost here.

> I think if you just replace the existing installed application it doesn't raise this again but if you delete and reinstall it does?

Just tried replacing with an upgraded version on macOS Big Sur 11.4, and it is making me jump through the security hoops again. I think that Catalina changed the security system...

**Comment by mattDavo** [comment]
> Oh ok, understood. Wonder if a possibility for donations (eg. GitHub Sponsors, Patreon, Open Collective, etc) would help to offset the cost here.

Yeah have thought about it, might consider it if adoption continues to increase.

> Just tried replacing with an upgraded version on macOS Big Sur 11.4, and it is making me jump through the security hoops again. I think that Catalina changed the signing system to be more strict...

Ah yeah I think so...
