### ISSUE TITLE
Add smaller centered window size option

### ISSUE THREAD

**Issue by Fischmuetze** [mattDavo/Yippy#27]
Hi,
would be great to have the tool available in a repository for installing it via home brew cask.

Also I would like to prefer smaller figures to display yippy ... for my eye it comes mostly much to big 
Even the small sized center window is very huge on 27" screen. 
Currently I'm using Clipy since years and Yippy could be an suiting candidate to rep,ace that but it should not appear linke a screen eater.

**Comment by jk** [comment]
Same as https://github.com/mattDavo/Yippy/issues/19

**Comment by mattDavo** [comment]
Resolved in https://github.com/mattDavo/Yippy/releases/tag/2.6.0

**Comment by mattDavo** [comment]
Resolved in https://github.com/mattDavo/Yippy/releases/tag/2.6.0
