### ISSUE TITLE
Error copying in Libreoffice Calc

### ISSUE THREAD

**Issue by Palmuser56** [mattDavo/Yippy#29]
Hello,

first of all: Thanks for Yippy. It is really a great tool.

When I copy a cell in LibreOffice Calc I get something like "Failed to save new pasteboard item due to error: The item couldn’t be saved because the file name “dyn....weqbc” is invalid."
Nevertheless the text was copied to Yippy. Hence everything seems to work fine but the window with the message is annoying.

Best regards
Michael

**Comment by mattDavo** [comment]
Resolved in https://github.com/mattDavo/Yippy/releases/tag/2.6.0
