### ISSUE TITLE
Do not create a new entry for duplicate content (option? default on?)

### ISSUE THREAD

**Issue by karlhorky** [mattDavo/Yippy#33]
Hi @mattDavo ! 👋

One idea that I've had when using Yippy extensively over the last months is this workflow:

1. Copy a piece of text repeatedly (because sometimes hitting cmd-C doesn't register)
2. There are now multiple duplicate entries in the clipboard manager, pushing some of the older history off the screen

What do you think of adding functionality to prevent creating a new history item if the copied content is the same as the last item?

I'm not sure why anyone would want to have duplicate items, but I suppose in case that would be a use case, it could be an option (would suggest defaulting to `on`).

Thanks for your hard work here!

**Comment by mattDavo** [comment]
Hey @karlhorky, glad to hear that all the bugs haven't been painful enough to drive you away 😅 Yep this one is on my radar and going to do it soon: https://github.com/mattDavo/Yippy/issues/8

Closing this issue since it's a duplicate.

**Comment by karlhorky** [comment]
Ah weird, I searched for "deduplication" in the issues 🤔 I guess the GitHub search isn't up to the task...

> glad to hear that all the bugs haven't been painful enough to drive you away 😅

Oh, not by a long shot! Yippy is by far the best clipboard manager I've ever used 💯 Great work.

**Comment by mattDavo** [comment]
> Oh, not by a long shot! Yippy is by far the best clipboard manager I've ever used 💯 Great work.

Alright haha, curious what you find better than alternatives? I just had a quick look on [Product Hunt](https://www.producthunt.com/search/posts?q=clipboard%20manager) and some seem quite good, albeit not free 😅 

@karlhorky

**Comment by karlhorky** [comment]
> curious what you find better than alternatives

Well I suppose there are fancy alternatives, and they offer a bunch of extra features, but my needs are pretty simple: I just want to be able to copy multiple times (normally only on a bunch of text) and have that show up in a multi-line list. I also use it sometimes to remove formatting from text, but this is not a huge dealbreaker feature normally. Yippy does a lot of things great, and it's minimal and lightweight.

And also, it's really nice to have it open source, with approachable maintainers. I may contribute in the future, if I manage to find some time to learn Swift. I'd like to get into macOS development so I can solve more of my own problems (although what I really want is to know how to use all [the private APIs](https://github.com/bdkjones/MuzzleApp/issues/90#issuecomment-770360232), so that I can customize everything)

I was using [Flycut](https://github.com/TermiT/Flycut) and [Maccy](https://github.com/p0deje/Maccy) before this, but they lacked on some of these things above.

**Comment by mattDavo** [comment]
Ahh cool, thanks for the detailed answer and I appreciate the support!

> I'd like to get into macOS development so I can solve more of my own problems (although what I really want is to know how to use all the private APIs, so that I can customize everything)

Ah yeah nice, I would like to more as well but in my (fairly limited) macOS development I've found it can be hard to make certain things work (like in that thread). Similarly with Yippy, I'd like to be able to have it on the App Store, but it simply wouldn't be accepted with the way I make it paste on enter. There are workarounds (like installing a helper app) and I would like to do it one day but it's annoying. Not to deter you 😜
