### ISSUE TITLE
Delete Shortcut No Longer Working?

### ISSUE THREAD

**Issue by karlhorky** [mattDavo/Yippy#38]
Hey @mattDavo ! 👋 Hope you're well.

I'm on 2.8.1 and it seems like in one of the last versions, the delete shortcut key (<kbd>cmd</kbd>-<kbd>backspace</kbd>) no longer works.

In 2.8.0 and 2.8.1 it also makes a \*beep\* error sound.

The delete function works from the menu.

**Comment by karlhorky** [comment]
Oh wait, I was reading the shortcut wrong - I guess it is not <kbd>cmd</kbd>-<kbd>backspace</kbd> - it's <kbd>ctrl</kbd>-<kbd>backspace</kbd>! This is working now! Closing.

**Comment by mattDavo** [comment]
Ah yep was just about to say. Thanks. I did this to better support the search bar, to allow clear left with  <kbd>cmd</kbd>-<kbd>backspace</kbd>.

Although I have now just realised that delete is broken when searching.

Cheers!
