### ISSUE TITLE
Preview pop up not triggering on spacebar press

### ISSUE THREAD

**Issue by paw-lu** [mattDavo/Yippy#47]
Pressing the spacebar when a snippet is highlighted does not seem to trigger a pop-up preview.

---

Thanks for sharing this tool, it's been really useful!

**Comment by drej1** [comment]
Hi @paw-lu , you have to press control + space

**Comment by paw-lu** [comment]
Works!

Thank you so much @drej1.

I'll mark this as closed, but might be good to update the site to reflect that!

<img width="1649" alt="Screen Shot 2021-08-27 at 8 31 30 AM" src="https://user-images.githubusercontent.com/30049606/131152262-a938bc82-283a-4ae9-937f-d390ca2d31b2.png">

**Comment by dr-format-d** [comment]
This should also be changed in the help section of the App itself. Just found the app and love it's potential. But i'm afraid this is abandoned?
<img width="435" alt="grafik" src="https://user-images.githubusercontent.com/110388306/199494635-bb2766af-db03-4d83-b319-dee34d17edad.png">
