### ISSUE TITLE
Copy from apps

### ISSUE THREAD

**Issue by neonfit** [mattDavo/Yippy#55]
Dear @mattDavo!
First of all thank you for this amazing app that made my life easier =)

I found a problem that it is impossible to add to clipboard for example a screenshot from Lightshot or a password from Dashlane...
Am I doing something wrong or it is not possible to have this feature in Yuppy?

Thanks in advance and thank you for your job!

**Comment by posguy99** [comment]
You almost certainly do not want a clipboard manager capturing items put on the clipboard by Dashlane.

**Comment by neonfit** [comment]
@posguy99 
Ok, Dashlane wasn’t a good idea, but what’s about Lightshot? Is there any hope? 
thanks
