### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by mattDavo** [mattDavo/Yippy#6]
Add the option for search functionality.

@alongouldman and anyone interested, how would Search be most beneficial? A fuzzy search, exact substring search or exact prefix search. Obviously some are more costly than others, especially as the number of saved items grows. Any thoughts and ideas would be great!

_Originally posted by @alongouldman in https://github.com/mattDavo/Yippy/issues/1#issuecomment-590771569_

**Comment by alongouldman** [comment]
What exactly do you mean by fuzzy search? IMO the best is substring search, case insensitive. 
for the number of items - isn't that an issue in general? Is there no limit for the number of items? would that not crack the computer memory eventually? 
if you limit the number of items (even 1000) that is enough, and I think search would be quick.

**Comment by mattDavo** [comment]
A fuzzy search is approximate string matching, see (https://en.wikipedia.org/wiki/Approximate_string_matching). But yeah there isn't a limit in the number of items, but I think I will have to add that soon.

Regardless, I agree, I think a case insensitive substring search would be best.

**Comment by justbilt** [comment]
Any roadmap or progress for this feature ? I think it's basic fucntion that you clipbaord-manager heavy user.

**Comment by mattDavo** [comment]
Hi @justbilt I'm sorry I haven't been able to add it yet. Hopefully, I can get it done in the coming months!

**Comment by lodestone** [comment]
Hi, I just found **Yippy** and I am impressed with it so far. 👍

Let me preface this with, I don't know what is or isn't easy or hard with Swift.

_On dealing with the size of the history_, in an ideal case the search would fire off and in the background would start churning through items (starting with the most recent) and update the UI as soon as matches are found. That would make the size of the history less of an issue. Of course, there would need to be some indication that the search is still going and if you wait there could be more matches.

_On fuzzy vs exact substring_, can we have both? Display the exact substring matches first and the fuzzy matches after?

**Comment by mattDavo** [comment]
Hi @lodestone, thank you for your support!

I am sorry I have been quite slack with working on this feature.

Yeah that's a good point, and I am no longer too concerned with the performance of search but just the other implementation details.

Having both fuzzy and exact substring is a great idea; I'll make sure that is how I do it eventually if not initially.

I will take a look this weekend to determine how much work is required to implement search and try to provide an estimation.

Cheers 😄

**Comment by mattDavo** [comment]
Hi all, I'm sorry this feature requires a fair bit of work which I cannot commit to at the moment. Hopefully, I'll have the time in a few months, when I have a few less commitments 😄
