### ISSUE TITLE
Better multiple screen support

### ISSUE THREAD

**Issue by mattDavo** [mattDavo/Yippy#7]
Feature request for opening the Yippy window on the screen the mouse is currently on. Currently the Yippy window only shows on the main screen. Would this mean that the Yippy window should be shown on all screens 😬or just the screen the mouse is on? If the Yippy window is open, should move across screens with the mouse or not until it is closed and re-opend.

_Originally posted by @alongouldman in https://github.com/mattDavo/Yippy/issues/1#issuecomment-590771569_

**Comment by alongouldman** [comment]
IMO:
1. not in all screens - just the main one
2. once opened, it will stay in that monitor even if the mouse moved. Yippy window will only change place after closed and reopened. 
3. to determine what monitor to open the window in, you *can* use mouse position - but I think there is also a thing in mac that chooses the focused window (maybe determined by a click? I am not sure). this could also be an indicator. But I think mouse location is better

**Comment by mattDavo** [comment]
OK sounds good, I'll see if I can determine the focused window.

**Comment by mattDavo** [comment]
Resolved in [2.4.0](https://github.com/mattDavo/Yippy/releases/tag/2.4.0) except that the window will follow the mouse across screens while open. If this is a major issue, I can add both options. It just seemed a bit unnatural, that's all. 😄
